### ISSUE TITLE
Add gamification features

### ISSUE THREAD

**Issue by kundlatsch** [arthuregood/pokesim__bot#1]
Some sugestions to make the bot more game-like in this early stages:

1. **Random pokémon encounters:** Instead of a command to search for pokémons, make them appear ramdomly based on the number of messages sended in the chat (the bot can store the number of messages sended without storing the content, to keep the user's privacy).

2. **First form encounters only:** Instead of appearing any random pokémon from the game, only first forms should appear (or at least more frequently). Also could remove the legendary pokémon (or make them realy hard to find), and users could choose a starter pokémon (and remove the starters from random encounters).

3. **Active pokémon:** Users could choose a pokémon to be active, and the pokémon would get EXP from the number of messages the user send on the chat (this requires a lot of work on the database, but would be really nice).

**Comment by arthuregood** [comment]
Opened new issues for each specific suggestion.
#2 - Random pokémon encounters
#3 - First form encounters only
#4 - Active pokémon
